# Generated by Django 5.1.6 on 2025-03-04 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0001_initial"),
        ("tpo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregistration",
            name="custom_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudentTraining",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="student.studentprofile",
                    ),
                ),
                (
                    "training_program",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "score_secured",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("max_score", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="placement_offers",
            field=models.ManyToManyField(
                blank=True, through="tpo.PlacementOffer", to="tpo.company"
            ),
        ),
    ]
